/* 
Natural join:
1 - at least one column has to be the same

*/

SELECT * FROM STUDENT NATURAL JOIN GRADE;

/* FIND THE NAME, MARKS, */
SELECT NAME, MARKS FROM STUDENT NATURAL JOIN GRADE WHERE MARKS BETWEEN 35 AND 100;

SELECT NAME, SNAME FROM STUDENT NATURAL JOIN GRADE NATURAL JOIN COURSE;

/* SUBJECT NAME, STUDENTID */
SELECT SNAME, S_ID FROM GRADE NATURAL JOIN COURSE;

SELECT NAME, MARKS FROM STUDENT NATURAL JOIN GRADE;

/* 
OUTER JOIN

*/

/* LEFT OUTER JOIN*/

SELECT * FROM STUDENT LEFT JOIN GRADE ON STUDENT.S_ID = GRADE.S_ID;

/* RIGHT OUTER JOIN*/
SELECT * FROM STUDENT RIGHT JOIN GRADE ON STUDENT.S_ID = GRADE.S_ID;
