/* CROSS JOIN  (NOT USED OFTEN) */
SELECT * FROM STUDENT CROSS JOIN GRADE;


/* CONDITIONAL JOIN */
SELECT * FROM STUDENT,GRADE WHERE STUDENT.S_ID = GRADE.S_NO;

/* NAME, MARKS AND S_CODE WHICH S_ID IS */
SELECT NAME, MARKS, SCODE FROM STUDENT, GRADE WHERE STUDENT.S_ID = GRADE.S_NO AND STUDENT.S_ID = 'S101';


/* fIND SUBJECT NAME, STUDENT ID CORRESPONDING TO THE SUBJECT CODE*/
SELECT SNAME, S_NO, COURSE.SCODE FROM COURSE,GRADE, STUDENT WHERE STUDENT.S_ID=GRADE.S_NO AND COURSE.SCODE = GRADE.SCODE;

/* FIND THE NAME, MARKS OF STUDENTS WITH MARK RANGE  */
SELECT NAME, MARKS FROM STUDENT,GRADE WHERE STUDENT.S_ID = GRADE.S_NO AND MARKS BETWEEN 35 AND 100;

/* FIND NAME OF THE STUDENT SUBJECT CODE OF STUDENT WHO HAVE NOT OPT IN TO PR1*/
SELECT NAME, SCODE FROM STUDENT, GRADE WHERE STUDENT.S_ID = GRADE.S_NO AND GRADE.SCODE != 'PR1';

/* FIND ST NUMBER, SUBJECT CODE AND MARKS WHOSE MARKS ABOVE 50 AND SUBJECT CODE IS EITHER PR1 OR PR2*/
SELECT S_NO, SCODE, MARKS FROM GRADE WHERE MARKS > 50 AND SCODE IN ("PR1","PR2");

/* NAME OF STUDENT AND SUBJECT CODE WHOSE SUBJECT STARTS WITH CHARACTER P*/
SELECT NAME, SCODE FROM STUDENT,GRADE WHERE STUDENT.S_ID=GRADE.S_NO AND SCODE LIKE "P%";

/* FIND NUMBER OF STUDENT SUBJECT WISE WHOSE MARKS IS MORE THAN 30 A LOOK INTYO GRPUP BY*/
SELECT SCODE, COUNT(*) AS "NUM OF STUDENT" FROM GRADE WHERE MARKS > 30 GROUP BY SCODE;


/* FIND AVAG MARKS OF STUDENTS SUBJECT WISE */
SELECT SCODE, AVG(MARKS) FROM GRADE GROUP BY SCODE;

/* HIGHEST MARKS IN EACH SUBJECT */
SELECT SCODE, MAX(MARKS) FROM GRADE GROUP BY SCODE;

/* FIND NAME, SUBJECT CODE AND MARKS OF THE STUDENT WHO HAVE SCORED HIGHEST MARKS*/
SELECT NAME, SCODE, MARKS FROM STUDENT, GRADE WHERE STUDENT.S_ID=GRADE.S_NO AND MARKS = (SELECT MAX(MARKS) FROM GRADE);

/* FIND HIGHEST FOR EACH MODULE*/

/* FIND NAME, SUBJECT CODE AND MARKS WHO HAVE SCORED THE LOWEST MARKS IN THE SUBJECT FLP*/
SELECT NAME, SCODE, MARKS FROM STUDENT, GRADE WHERE STUDENT.S_ID=GRADE.S_NO AND GRADE.SCODE = "FLP" AND MARKS = (SELECT MIN(MARKS) FROM GRADE);

/* GIVE ADD 10% MARKS AND DISPLAY WITH STIDENT NAME AND SUBJECT CODE*/
SELECT NAME, SCODE, MARKS + (MARKS * 0.10) AS "MARKS + 10%" FROM STUDENT, GRADE WHERE STUDENT.S_ID = GRADE.S_NO;


/* FIND THE STUDENT NQAMER WITH SUBJECT NAME*/
SELECT NAME,  SNAME FROM STUDENT, COURSE, GRADE WHERE STUDENT.S_ID = GRADE.S_NO AND COURSE.SCODE = GRADE.SCODE;

/*FIND STUDENT NAME, MARKS AND SUBJECT NAMER WHO HAVE SCORED HIGHESTY MARKS*/
SELECT NAME,  SNAME, MARKS FROM STUDENT, COURSE, GRADE WHERE STUDENT.S_ID = GRADE.S_NO AND COURSE.SCODE = GRADE.SCODE AND GRADE.MARKS = (SELECT MAX(MARKS) FROM GRADE);
