/* lesson 4*/


/*ORDER BY*/
SELECT * FROM CUSTOMER ORDER BY GRADE;

/*AGRAGATE FUNCTION SUM, AVG, COUNT, MAX, MIN */
SELECT SUM(GRADE) AS TOTAL_GRADE FROM CUSTOMER;

SELECT MAX(GRADE) AS MAX_GRADE, MIN(GRADE) AS MIN_GRADE FROM CUSTOMER;

SELECT SUM(GRADE) as TOTAL_GRADE FROM CUSTOMER WHERE CITY="New York";



SELECT SUM(GRADE) AS TOTAL_GRADE FROM CUSTOMER WHERE GRADE BETWEEN 200 AND 300;

SELECT MAX(GRADE) AS MAX_GRADE FROM CUSTOMER WHERE CITY="Berlin" OR CITY="Paris" OR CITY="California";


SELECT MAX(GRADE) AS MAX_GRADE FROM CUSTOMER WHERE CITY IN("Berlin","Paris","California");

SELECT AVG(GRADE) AS "avg grade" FROM CUSTOMER WHERE SALESMAN_ID=5001;

SELECT MIN(GRADE) AS "avg grade" FROM CUSTOMER WHERE CITY IN("London","New York");

select count(*) as num_records from customer where grade = 200;

/*NESTED QUERY*/
SELECT CUST_NAME FROM CUSTOMER WHERE GRADE = (SELECT MAX(GRADE) FROM CUSTOMER);
SELECT CUST_NAME FROM CUSTOMER WHERE GRADE = (SELECT MIN(GRADE) FROM CUSTOMER);


/* UTITLITY FUNCTIONS*/
/* NAME THAT START WITH B*/
SELECT CUST_NAME FROM CUSTOMER WHERE CUST_NAME LIKE "B%"; 

